### ISSUE TITLE
additive_seasonality *= self.data.y.max()

### ISSUE THREAD

**Issue by dsvolk** [luke14free/pm-prophet#10]
I've been reading through the code and I met this line at model.py, line 293:
`additive_seasonality *= self.data.y.max()`
and in a few other places around the code. Could anyone comment on its exact purpose?

This seems to me to be related to data standartisation, but data standartisation is also done later, in the model specification:
`observed=(self.data['y'] - self.data['y'].mean()) / self.data['y'].std()`

At the very least, shouldn't it be 
`additive_seasonality *= self.data.y.abs().max()` 
to account for the possiblity that, say, range of y is [-1,0] and thus y.max()==0 ?

**Comment by luke14free** [comment]
Fair point. thanks for noticing

**Comment by dsvolk** [comment]
You're welcome :)
