### ISSUE TITLE
license

### ISSUE THREAD

**Issue by JoeyFaulkner** [luke14free/pm-prophet#13]
hey there! could you attach a license to this repo? Am I free to fork it and use it? (https://help.github.com/articles/licensing-a-repository/) Thanks!

**Comment by twiecki** [comment]
@luke14free I recommend Apache v2.

**Comment by twiecki** [comment]
@JoeyFaulkner But I'm pretty sure you can go ahead and fork and use it in the meantime, otherwise it wouldn't be up here.

**Comment by luke14free** [comment]
👍yes, super fine to go with apache V2 (feel free to do a PR). please go ahead with your fork, but if you want to contribute anything I'd be super happy to include in this repo

**Comment by JoeyFaulkner** [comment]
awesome! :) we're working on some stuff and will keep you updated if anything cool comes from it. Thanks for the code!
