### ISSUE TITLE
Would you like to consider adding this to pymc-learn and pymc3-models?

### ISSUE THREAD

**Issue by ericmjl** [luke14free/pm-prophet#14]
As per title! :smile: I like a lot of what's going on here, and would love to see a few things happen:

- Reduce your maintenance burden.
- Package this model implementation with other "standard" but also "flexible" models.
- Reduce end-user environment complexity by packaging together things that are clearly related.

cc: @emaasit, creator of pymc-learn, and @parsing-science, creator of pymc_models.

**Comment by luke14free** [comment]
I am not entirely sure this library is a good fit for those packages, so I am passing on this atm. But I will definitely consider it in the future. Thanks
