### ISSUE TITLE
Is GPU included?

### ISSUE THREAD

**Issue by JafferWilson** [luke14free/pm-prophet#20]
Hello Developers of this wonderful repository,
I have tried samples. It looks good. But I haven't got any settings for the usage of GPU. It works with the CPU only. What if I am willing to go with the GPUs in my system for the training?
Can you help and guide me?

**Comment by luke14free** [comment]
Hi there, this strongly depends on theano and pymc3 under the hood, which currently relies on Theano (which is discontinued). In theory I think you can use AVDI with GPU, but refer to pymc3 and theano documentations for the setup.
