### ISSUE TITLE
auto_changepoint issue

### ISSUE THREAD

**Issue by BjorHart** [luke14free/pm-prophet#22]
Hi!
I am trying to use the pm-prophet feature auto_changepoints to detect changepoints in a dataset. It gives seemingly good results, but when running the script on the same dataset twice, the inferred changepoints are located different places. How can i make the auto_changepoints more accurate? does this have to do with my sample size?

**Comment by luke14free** [comment]
Try increasing the burn-in, have a better sample, model specification or priors. Nothing much we can do about the random nature of the priors 🙃
