### ISSUE TITLE
do you have example  to use your code like prophet with multiple regressores ?

### ISSUE THREAD

**Issue by Sandy4321** [luke14free/pm-prophet#28]
do you have example  to use your code like prophet with multiple regressores ?

https://github.com/facebook/prophet/issues/1410

or

y(t) = trend(t) + seasonality(t) + beta1 * regressor1(t) + beta2 * regressor2(t) + ...

**Comment by luke14free** [comment]
Please read the answer from the issue you posted. It's basically the same with pm-prophet.

Just model your regressors with pandas and then add the various regressors with: model.add_regressor('regressorX')
