### ISSUE TITLE
ValueError: Of the three parameters: start, end, and periods, exactly two must be specified

### ISSUE THREAD

**Issue by twolodzko** [luke14free/pm-prophet#3]
When running the examples from model.py and readme I get the following error:

`ValueError: Of the three parameters: start, end, and periods, exactly two must be specified`

**Comment by luke14free** [comment]
are you observing this on the provided dataset? which version of pandas are you using?

**Comment by twolodzko** [comment]
Yes, it was pandas version. I saw you changed it in `setup.py`, so it can be closed.
