### ISSUE TITLE
Updated readme for project direction?

### ISSUE THREAD

**Issue by michael-ziedalski** [luke14free/pm-prophet#9]
As it is, it is hard to gain a sense of where this project is going, or what needs to still be done (and what exactly has been accomplished), which an updated readme would solve.

Not only would this improve readability, but help others help out with contributions as well.

**Comment by luke14free** [comment]
Answering this very late, apologies, but can you be a bit more specific? What would you like to know?

**Comment by michael-ziedalski** [comment]
Essentially, this is what I would (and, I imagine, other potential contributors as well) like to see:
1. What kind of time series models you are planning to implement (have ideas for already, are easy extensions of the existing codebase, etc)
2. What kind of time series models do you think are possible, but would require some creativity to implement (as an example, multiplicative models vs. the additive model setup currently in place)?

What I think would be most beneficial, for a wide-scoped project like pm-prophet, is a whishlist akin to what Stan has, for example.

**Comment by luke14free** [comment]
Answering & closing.

> What kind of time series models you are planning to implement (have ideas for already, are easy extensions of the existing codebase, etc)

In this current repository I am not planning to implement things other than the prophet model. I believe every project should have a delimited scope.

> What kind of time series models do you think are possible, but would require some creativity to implement (as an example, multiplicative models vs. the additive model setup currently in place)?

Multiplicative seasonality is already implemented. The only main missing thing from the original prophet is Logistic growth as you can read from the readme.

I don't believe this project has a scope as wide as stan or pymc :) I will nevertheless add a wiki page as it seems like a good choice (thanks for the tip).
